# Generated by Django 4.0 on 2021-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbin',
            name='version',
            field=models.CharField(default='-', max_length=5),
            preserve_default=False,
        ),
    ]
