# Generated by Django 4.0 on 2021-12-27 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('99a9954b-2436-45d7-8e6f-6747835a760f'), editable=False),
        ),
    ]
