# Generated by Django 4.0 on 2021-12-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0006_alter_server_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='uuid',
        ),
        migrations.AddField(
            model_name='server',
            name='identifier',
            field=models.CharField(default='', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
