# Generated by Django 4.0 on 2021-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0007_remove_server_uuid_server_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverbin',
            name='binary_name',
            field=models.CharField(blank=True, help_text='this gets set when saving', max_length=200),
        ),
    ]
