# Generated by Django 4.0 on 2021-12-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0008_serverbin_binary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_pid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
