# Generated by Django 4.0 on 2021-12-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0009_server_server_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverbin',
            name='type',
            field=models.IntegerField(choices=[(0, 'BungeeCord'), (1, 'Spigot'), (2, 'Bukkit'), (3, 'PaperMC'), (4, 'Vanilla')], default=0),
        ),
    ]
