# Generated by Django 3.2.10 on 2022-01-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0010_alter_serverbin_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': (('op', 'Is OP'),), 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
    ]
