# Generated by Django 3.2.10 on 2022-01-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0011_alter_server_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'permissions': (('op', 'Is OP'), ('restart_server', 'Can restart Server')), 'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
    ]
